import { OPEN_SOURCE_DEMOS } from "./open-source-demos";
import type { Demo, DemoCategory } from "./demo-types";

export type { Demo, DemoCategory, OssKind } from "./demo-types";
export { OPEN_SOURCE_DEMOS } from "./open-source-demos";

/** ระบบธุรกิจม็อกอัพ (กดลองได้) — ชื่อสมมติทั้งหมด */
export const SYSTEM_DEMOS: Demo[] = [
  {
    slug: "erp",
    name: "LCS Enterprise ERP",
    category: "ระบบหลังบ้าน",
    icon: "dashboard",
    tagline: "ERP สำหรับธุรกิจนำเข้า–จัดจำหน่าย B2B",
    description:
      "เดโม ERP ตัวเต็มสำหรับธุรกิจนำเข้าและจัดจำหน่าย B2B ครบตั้งแต่ CRM, Sourcing, Sales, Purchasing, Import, Landed Cost, Inventory, Finance จนถึง Customer Portal",
    preview: "/showcase/erp.jpg",
    swatch: "from-[#071a34] via-[#334155] to-[#94a3b8]",
    accentText: "text-[#0f2744]",
    tags: ["ERP", "Import", "B2B CRM"],
    features: [
      "เข้าสู่ระบบเดโมและเลือก Role ผู้ใช้งานได้",
      "เอกสาร CRM → Quotation → SO → PO → Shipment เชื่อมกันทั้งสาย",
      "Landed Cost, คลังสินค้า, Credit Control และรายงานกำไร",
    ],
  },
  {
    slug: "court-booking",
    name: "SmashLane Arena",
    category: "จองบริการ",
    icon: "calendar",
    tagline: "ระบบจองสนามแบด + หลังบ้านจัดคอร์ท",
    description:
      "ม็อกอัพใช้งานได้จริง: ลูกค้าเลือกช่วงเวลา ชำระเงินจำลอง แล้วแอดมินจัดเลขคอร์ทในตาราง มีคิวรอจัด Walk-in และล็อกรายเดือน",
    preview: "/showcase/court-booking.jpg",
    swatch: "from-[#3953A4] via-sky-500 to-[#EB8824]",
    accentText: "text-[#3953A4]",
    tags: ["จองคิว", "ตารางคอร์ท", "หลังบ้าน"],
    features: [
      "ฝั่งลูกค้า: เลือกวัน/ชั่วโมง ตะกร้า ชำระ PromptPay จำลอง",
      "ฝั่งแอดมิน: คิวรอจัดคอร์ท + ตารางคอร์ทกดจัดได้",
      "Walk-in / ล็อกรายเดือน / รีเซ็ตเดโม",
    ],
  },
  {
    slug: "fleet-ops",
    name: "BlueRoute Fleet",
    category: "ระบบหลังบ้าน",
    icon: "dashboard",
    tagline: "Dashboard งานซ่อมบำรุงรถ",
    description:
      "ม็อกอัพหลังบ้านบริษัทขนส่ง: งานประจำวัน งานค้างซ่อม เสียกลางทาง สรุปงานพร้อมอะไหล่ และค้นหารถ",
    preview: "/showcase/fleet-ops.jpg",
    swatch: "from-[#16234A] via-[#2E4A8A] to-[#C9A227]",
    accentText: "text-[#16234A]",
    tags: ["Job Order", "Dashboard", "ค้นหารถ"],
    features: [
      "ล็อกอินเดโม + Dashboard 3 การ์ดหลัก",
      "เจาะรายการงานตามช่าง / สถานะ",
      "สรุปงาน อะไหล่ ค่าใช้จ่าย + ค้นหาโปรไฟล์รถ",
    ],
  },
  {
    slug: "field-crm",
    name: "GuardNest Field",
    category: "ระบบหลังบ้าน",
    icon: "layers",
    tagline: "CRM / Job Order ทีมหน้างาน",
    description:
      "ม็อกอัพบริษัทบริการภาคสนาม: งานวันนี้ Quotation ปฏิทินทีม และ Dashboard — ติดตามสถานะงานถึงหน้างาน",
    preview: "/showcase/field-crm.jpg",
    swatch: "from-emerald-600 via-teal-500 to-cyan-600",
    accentText: "text-emerald-700",
    tags: ["CRM", "Quotation", "ทีมหน้างาน"],
    features: ["สถานะงานครบวงจร", "ใบเสนอราคาอนุมัติได้", "ปฏิทินทีม + KPI"],
  },
  {
    slug: "clinic-admin",
    name: "MediSlot Clinic",
    category: "จองบริการ",
    icon: "heart",
    tagline: "ระบบนัดหมายคลินิก + หลังบ้าน",
    description:
      "ม็อกอัพคลินิก: ผู้ป่วยจองคิวได้เอง แอดมินจัดการนัด ตารางหมอ และบันทึกผู้ป่วย",
    preview: "/showcase/clinic-admin.jpg",
    swatch: "from-cyan-500 via-teal-400 to-sky-600",
    accentText: "text-teal-700",
    tags: ["นัดหมาย", "ตารางหมอ", "CMS คนไข้"],
    features: ["จองบริการ/วัน/เวลา", "เช็คมาแล้ว–ไม่มา", "รายชื่อผู้ป่วย + โน้ต"],
  },
  {
    slug: "kitchen-board",
    name: "TableFlow Bistro",
    category: "ร้านอาหาร",
    icon: "coffee",
    tagline: "จองโต๊ะ + Kitchen Board + เมนู CMS",
    description:
      "ม็อกอัพร้านอาหาร: จองโต๊ะ กระดานครัวเลื่อนสถานะออเดอร์ และเปิด/ปิดเมนูพร้อมแก้ราคา",
    preview: "/showcase/kitchen-board.jpg",
    swatch: "from-amber-500 via-orange-400 to-rose-500",
    accentText: "text-amber-700",
    tags: ["จองโต๊ะ", "ครัว", "เมนู CMS"],
    features: ["จองโต๊ะหน้าร้าน", "บอร์ดครัว ใหม่→กำลังทำ→พร้อม", "เมนู sold-out / แก้ราคา"],
  },
  {
    slug: "hotel-pms",
    name: "StayNest Hotel",
    category: "ระบบหลังบ้าน",
    icon: "home",
    tagline: "PMS โรงแรม Front Desk + ห้องพัก",
    description:
      "ม็อกอัพโรงแรม: Front Desk check-in/out สถานะห้อง Housekeeping และรายการจอง",
    preview: "/showcase/hotel-pms.jpg",
    swatch: "from-slate-800 via-blue-900 to-amber-500",
    accentText: "text-amber-800",
    tags: ["Front Desk", "Rooms", "Housekeeping"],
    features: ["เช็คอิน–เช็คเอาต์วันนี้", "กริดสถานะห้อง", "งานแม่บ้านติ๊กเสร็จ"],
  },
  {
    slug: "gym-admin",
    name: "IronPulse Gym",
    category: "จองบริการ",
    icon: "rocket",
    tagline: "สมาชิก คลาส Check-in และแพ็กเกจ",
    description:
      "ม็อกอัพฟิตเนส: จัดการสมาชิก ตารางคลาส Check-in หน้าร้าน และแพ็กเกจ CMS",
    preview: "/showcase/gym-admin.jpg",
    swatch: "from-zinc-900 via-lime-500 to-orange-500",
    accentText: "text-lime-700",
    tags: ["สมาชิก", "คลาส", "Check-in"],
    features: ["ต่ออายุสมาชิก", "จองที่นั่งคลาส", "แพ็กเกจยอดนิยม"],
  },
  {
    slug: "ai-cms",
    name: "NovaOracle AI",
    category: "ระบบหลังบ้าน",
    icon: "spark",
    tagline: "Admin AI — Credits Personas CMS",
    description:
      "ม็อกอัพผลิตภัณฑ์ AI: จัดการผู้ใช้ Free/Pro เติมเครดิต Personas และบทความ CMS",
    preview: "/showcase/ai-cms.jpg",
    swatch: "from-violet-600 via-indigo-500 to-fuchsia-500",
    accentText: "text-violet-700",
    tags: ["Credits", "Persona", "CMS"],
    features: ["เติมเครดิตผู้ใช้", "เปิด/ปิด Persona + แก้ prompt", "บทความ draft/publish"],
  },
  {
    slug: "tutor-admin",
    name: "BrightSlot Tutor",
    category: "จองบริการ",
    icon: "calendar",
    tagline: "จองติวเตอร์ + หลังบ้านตารางสอน",
    description:
      "ม็อกอัพสถาบันกวดวิชา: ผู้ปกครองจองคิว แอดมินอนุมัติตาราง ดูโหลดติวเตอร์ และรายชื่อนักเรียน",
    preview: "/showcase/tutor-admin.jpg",
    swatch: "from-sky-500 via-blue-400 to-indigo-500",
    accentText: "text-sky-700",
    tags: ["จองคลาส", "ติวเตอร์", "นักเรียน"],
    features: ["จองวิชา/ติวเตอร์/เวลา", "อนุมัติ–ยกเลิกคิว", "โหลดงานติวเตอร์"],
  },
  {
    slug: "dispatch",
    name: "QuickDrop Logistics",
    category: "ระบบหลังบ้าน",
    icon: "cart",
    tagline: "Dispatch ออเดอร์ส่งของ + พนักงานส่ง",
    description:
      "ม็อกอัพโลจิสติกส์: เลื่อนสถานะออเดอร์ มอบหมายพนักงานส่ง โซนจัดส่ง และสรุปวัน",
    preview: "/showcase/dispatch.jpg",
    swatch: "from-indigo-600 via-blue-500 to-rose-400",
    accentText: "text-indigo-700",
    tags: ["Dispatch", "Courier", "โซน"],
    features: ["เลื่อนสถานะออเดอร์", "ออนไลน์พนักงาน + มอบหมายงาน", "KPI สรุปวัน"],
  },
  {
    slug: "laundry-ops",
    name: "FreshFold Laundry",
    category: "จองบริการ",
    icon: "layers",
    tagline: "เรียกรับผ้า · บอร์ดซัก · แพ็กเกจ CMS",
    description:
      "ม็อกอัพร้านซักรีด: ลูกค้าเรียกรับผ้า ทีมเลื่อนสถานะงาน แก้แพ็กเกจราคา และโน้ตลูกค้า",
    preview: "/showcase/laundry-ops.jpg",
    swatch: "from-[#2C5F4F] via-emerald-500 to-teal-400",
    accentText: "text-[#2C5F4F]",
    tags: ["เรียกรับผ้า", "บอร์ดงาน", "แพ็กเกจ"],
    features: ["ฟอร์มเรียกรับผ้า", "สถานะรับแล้ว→กำลังซัก→พร้อมส่ง→ส่งแล้ว", "แพ็กเกจ CMS + โน้ตลูกค้า"],
  },
  {
    slug: "cowork-desk",
    name: "NestDesk Cowork",
    category: "จองบริการ",
    icon: "home",
    tagline: "จอง Hot Desk · ห้องประชุม · Check-in",
    description:
      "ม็อกอัพ coworking: จองโต๊ะ/ห้องประชุม แคตตาล็อกพื้นที่ สมาชิก Check-in และภาพรวมวัน",
    preview: "/showcase/cowork-desk.jpg",
    swatch: "from-[#3D4F6F] via-slate-500 to-sky-400",
    accentText: "text-[#3D4F6F]",
    tags: ["Hot Desk", "Meeting", "Check-in"],
    features: ["จองโต๊ะ/ห้องพร้อมรูป", "ต่ออายุสมาชิก + Check-in", "แอดมินรายการจองวันนี้"],
  },
  {
    slug: "pet-clinic",
    name: "PawCare Vet Clinic",
    category: "จองบริการ",
    icon: "heart",
    tagline: "คลินิกสัตว์เลี้ยง · จองคิว + หลังบ้าน",
    description:
      "ม็อกอัพคลินิกสัตว์: เจ้าของจองคิวพร้อมชื่อสัตว์เลี้ยง แอดมินเช็คมาแล้ว/ไม่มา ตารางสัตวแพทย์ และ CMS ประวัติสัตว์",
    preview: "/showcase/pet-clinic.jpg",
    swatch: "from-[#5B4B8A] via-violet-400 to-fuchsia-300",
    accentText: "text-[#5B4B8A]",
    tags: ["จองคิว", "สัตวแพทย์", "CMS สัตว์เลี้ยง"],
    features: ["จองบริการพร้อมชื่อสัตว์เลี้ยง", "เช็คมาแล้ว–ไม่มา", "ตารางสัตวแพทย์ + ประวัติสัตว์"],
  },
  {
    slug: "venue-booking",
    name: "VenueHive",
    category: "จองบริการ",
    icon: "calendar",
    tagline: "จองห้องจัดเลี้ยง · อีเวนต์ + ใบเสนอราคา",
    description:
      "ม็อกอัพระบบจองฮอลล์: แกลเลอรีห้อง ความจุ/ราคา ขอจอง อนุมัติอีเวนต์ และใบเสนอราคา",
    preview: "/showcase/venue-booking.jpg",
    swatch: "from-[#6B3F3F] via-rose-400 to-amber-300",
    accentText: "text-[#6B3F3F]",
    tags: ["ฮอลล์", "อีเวนต์", "ใบเสนอราคา"],
    features: ["แกลเลอรีฮอลล์ + ความจุ/ราคา", "ขอจองและอนุมัติอีเวนต์", "ใบเสนอราคาอนุมัติได้"],
  },
  {
    slug: "auto-detail",
    name: "ShineAuto Detail",
    category: "จองบริการ",
    icon: "rocket",
    tagline: "จองคิวล้างรถ · เบย์ + สมาชิก",
    description:
      "ม็อกอัพคาร์แคร์: จองแพ็กเกจ+เบย์ บอร์ดตารางเบย์ เลื่อนสถานะงาน และสมาชิกสะสมแต้ม",
    preview: "/showcase/auto-detail.jpg",
    swatch: "from-[#1F3A5F] via-sky-500 to-slate-400",
    accentText: "text-[#1F3A5F]",
    tags: ["จองคิว", "เบย์", "สมาชิก"],
    features: ["จองแพ็กเกจ + เบย์", "สถานะงาน รอคิว→กำลังทำ→เสร็จ", "สมาชิกสะสมแต้ม"],
  },
];

export const CLIENT_WORK: Demo[] = [
  {
    slug: "nursego",
    name: "NurseGo",
    category: "ลูกค้าของเรา",
    icon: "heart",
    tagline: "แพลตฟอร์มหางานพยาบาล",
    description:
      "เว็บและแอปสำหรับพยาบาลหางาน พาร์ทไทม์ และองค์กรที่ต้องการบุคลากรทางการแพทย์ — โปรเจกต์จริงที่ออนไลน์แล้ว",
    liveUrl: "https://www.nursego.co/",
    preview: "/showcase/nursego.jpg",
    swatch: "from-sky-400 via-cyan-400 to-amber-300",
    accentText: "text-sky-600",
    tags: ["Healthcare", "Live", "Web + App"],
    features: ["หางานพยาบาล", "งานพาร์ทไทม์", "สำหรับองค์กร"],
  },
  {
    slug: "kindgo",
    name: "KindGo",
    category: "ลูกค้าของเรา",
    icon: "layers",
    tagline: "บริการในชีวิตประจำวัน จองได้ที่เดียว",
    description:
      "แพลตฟอร์มรวมบริการบ้าน ซ่อม ทำความสะอาด ดูแล และเดินทาง เชื่อมลูกค้ากับผู้ให้บริการที่ตรวจแล้ว",
    liveUrl: "https://kindgo.app/",
    preview: "/showcase/kindgo.jpg",
    swatch: "from-orange-400 via-amber-400 to-yellow-300",
    accentText: "text-orange-600",
    tags: ["Marketplace", "Booking", "Live"],
    features: ["เลือกบริการ + พิกัด", "จองวันเวลา", "ติดตามงานและชำระเงิน"],
  },
  {
    slug: "horasard",
    name: "Horasard",
    category: "ลูกค้าของเรา",
    icon: "spark",
    tagline: "ดูดวงด้วย AI จากพื้นดวงจริง",
    description:
      "เว็บโหราศาสตร์คำนวณลัคนาและดาวพื้นดวงจากวันเกิด แล้วสนทนา AI ตามหมวด พร้อมแพ็กเกจ Free / Pro",
    liveUrl: "https://horasard.com/",
    preview: "/showcase/horasard.jpg",
    swatch: "from-stone-900 via-amber-700 to-amber-400",
    accentText: "text-amber-700",
    tags: ["AI Chat", "Membership", "Live"],
    features: ["คำนวณพื้นดวง", "สนทนาตามหมวด", "เครดิตและแพ็กเกจ Pro"],
  },
  {
    slug: "sirikanchana",
    name: "Sirikanchana",
    category: "ลูกค้าของเรา",
    icon: "calendar",
    tagline: "จองคอร์ทแบดมินตันออนไลน์",
    description:
      "ระบบจองสนามแบดศิริกาญจนา 25 คอร์ท จองตามช่วงเวลา หลายคอร์ท ชำระ PromptPay — เว็บจริงที่ออนไลน์แล้ว",
    liveUrl: "https://sirikanchana.com/",
    preview: "/showcase/sirikanchana.jpg",
    swatch: "from-[#3953A4] via-orange-500 to-orange-400",
    accentText: "text-[#3953A4]",
    tags: ["Booking", "Live", "Sports"],
    features: ["จองหลายช่วง หลายคอร์ท", "ชำระ PromptPay", "สมาชิก LINE"],
  },
  {
    slug: "sombattour",
    name: "สมบัติทัวร์",
    category: "ลูกค้าของเรา",
    icon: "globe",
    tagline: "ระบบดิจิทัลภาคขนส่ง",
    description:
      "โปรเจกต์ในภาคธุรกิจขนส่งสำหรับ สมบัติทัวร์ — เว็บองค์กรและงานระบบที่ธุรกิจใช้จริง",
    liveUrl: "https://www.sombattour.com/",
    preview: "/showcase/sombattour.jpg",
    swatch: "from-blue-500 via-sky-400 to-orange-400",
    accentText: "text-blue-700",
    tags: ["Transportation", "Live"],
    features: ["เว็บองค์กร", "ช่องทางจองตั๋ว", "งานระบบภายใน"],
  },
  {
    slug: "marketimes-asia",
    name: "Marketimes Asia",
    category: "ลูกค้าของเรา",
    icon: "globe",
    tagline: "แพลตฟอร์มสื่อและคอนเทนต์",
    description:
      "เว็บไซต์สื่อและคอนเทนต์ออนไลน์สำหรับ Marketimes Asia โชว์ข่าว บทความ และแบรนด์สำนักข่าว",
    liveUrl: "https://marketimesasia.com/",
    preview: "/showcase/marketimes-asia.jpg",
    swatch: "from-rose-500 via-red-500 to-slate-800",
    accentText: "text-rose-700",
    tags: ["Publishing", "CMS", "Live"],
    features: ["หน้าสื่อออนไลน์", "หมวดคอนเทนต์", "แบรนด์สำนักข่าว"],
  },
];

export const DEMOS: Demo[] = [
  ...CLIENT_WORK,
  ...SYSTEM_DEMOS,
  {
    slug: "restaurant",
    name: "BISTRO CAFÉ",
    category: "ร้านอาหาร",
    icon: "coffee",
    tagline: "เว็บร้านอาหาร / คาเฟ่ + จองโต๊ะ",
    description:
      "ตัวอย่างเว็บร้านอาหารสไตล์พรีเมียม โทนครีม-อบอุ่น โชว์เมนูแยกหมวด ระบบจองโต๊ะ และแผนที่ร้าน",
    preview: "/showcase/restaurant.jpg",
    swatch: "from-amber-400 via-orange-400 to-rose-400",
    accentText: "text-amber-700",
    tags: ["เมนูออนไลน์", "จองโต๊ะ", "แผนที่"],
    features: ["เมนูแยกหมวด พร้อมราคา", "ฟอร์มจองโต๊ะเลือกวัน-เวลา-จำนวนคน", "ข้อมูลติดต่อและแผนที่ร้าน"],
  },
  {
    slug: "shop",
    name: "SweetShop",
    category: "ขายของ",
    icon: "cart",
    tagline: "เว็บขายของออนไลน์ + ตะกร้า + ชำระเงิน",
    description:
      "ตัวอย่างร้านค้าออนไลน์โทนพาสเทลน่ารัก มีหน้าสินค้า ตะกร้า เลือกวิธีชำระเงิน และสรุปออเดอร์",
    preview: "/showcase/shop.jpg",
    swatch: "from-rose-400 via-pink-400 to-fuchsia-400",
    accentText: "text-pink-600",
    tags: ["แคตตาล็อก", "ตะกร้า", "ชำระเงิน"],
    features: ["หน้าสินค้าพร้อมราคา", "ตะกร้าสินค้าแบบเรียลไทม์", "เลือกวิธีชำระเงิน + สรุปออเดอร์"],
  },
  {
    slug: "booking",
    name: "Glow Beauty & Wellness",
    category: "จองบริการ",
    icon: "calendar",
    tagline: "ระบบจองบริการ / นัดหมาย",
    description:
      "ตัวอย่างระบบนัดหมายสำหรับคลินิก ร้านเสริมสวย และฟิตเนส เลือกบริการ ปฏิทิน เวลา และยืนยันพร้อมแจ้งเตือน",
    preview: "/showcase/booking.jpg",
    swatch: "from-violet-400 via-purple-400 to-fuchsia-400",
    accentText: "text-violet-700",
    tags: ["เลือกบริการ", "ปฏิทิน + เวลา", "แจ้งเตือน"],
    features: ["เลือกบริการพร้อมราคา/ระยะเวลา", "ปฏิทินและช่วงเวลาว่าง", "ยืนยันพร้อมแจ้งเตือนนัดหมาย"],
  },
  {
    slug: "dashboard",
    name: "LCS Business Dashboard",
    category: "ระบบหลังบ้าน",
    icon: "dashboard",
    tagline: "ระบบหลังบ้าน / เว็บเฉพาะธุรกิจ",
    description:
      "ตัวอย่างระบบหลังบ้านโทน Dark Tech มีภาพรวมธุรกิจ KPI กราฟยอดขาย ตารางออเดอร์ และสินค้าขายดี",
    preview: "/showcase/dashboard.jpg",
    swatch: "from-blue-600 via-sky-500 to-slate-800",
    accentText: "text-blue-700",
    tags: ["KPI", "กราฟยอดขาย", "ตารางออเดอร์"],
    features: ["การ์ดสรุปยอดขาย/ออเดอร์", "กราฟยอดขาย + โดนัทสัดส่วน", "ตารางออเดอร์ + สินค้าขายดี"],
  },
  {
    slug: "corporate",
    name: "COMPANY",
    category: "เว็บบริษัท",
    icon: "globe",
    tagline: "เว็บไซต์บริษัท โทนพรีเมียม",
    description:
      "ตัวอย่างเว็บไซต์บริษัทโทน Navy-Gold ดูน่าเชื่อถือ โครงสร้างครบ ตั้งแต่ Hero บริการ ผลงาน ไปจนถึงฟอร์มติดต่อ",
    preview: "/showcase/corporate.jpg",
    swatch: "from-slate-800 via-blue-900 to-amber-600",
    accentText: "text-amber-700",
    tags: ["องค์กร", "บริการ", "ติดต่อ"],
    features: ["Hero + ตัวเลขความน่าเชื่อถือ", "บริการ 4 ด้าน + ผลงาน", "ฟอร์มติดต่อทีมขาย"],
  },
  {
    slug: "ban-suk-jai",
    name: "Ban Suk Jai Residences",
    category: "อสังหาริมทรัพย์",
    icon: "home",
    tagline: "เว็บโครงการที่พักอาศัย / หอพัก",
    description:
      "เว็บไซต์โครงการที่พักอาศัย โชว์ข้อมูลโครงการ ห้องว่าง สิ่งอำนวยความสะดวก และช่องทางติดต่อสอบถาม",
    liveUrl: "https://test-cursor-one.vercel.app/",
    preview: "/showcase/ban-suk-jai.jpg",
    swatch: "from-teal-500 via-emerald-500 to-cyan-600",
    accentText: "text-teal-700",
    tags: ["ที่พักอาศัย", "ห้องว่าง", "ติดต่อสอบถาม"],
    features: ["หน้าแรกโชว์จุดเด่นโครงการ", "รายละเอียดห้องและราคา", "ฟอร์มติดต่อ / สอบถาม"],
  },
  {
    slug: "aurelia-residences",
    name: "Aurelia Residences",
    category: "อสังหาริมทรัพย์",
    icon: "home",
    tagline: "เว็บ Luxury Living / คอนโดพรีเมียม",
    description:
      "เว็บไซต์โทนหรูหรา สำหรับโครงการที่พักระดับพรีเมียม เน้นภาพลักษณ์ ยูนิต สิ่งอำนวยความสะดวก และนัดชมโครงการ",
    liveUrl: "https://rental-luxury.vercel.app/",
    preview: "/showcase/aurelia-residences.jpg",
    swatch: "from-slate-900 via-amber-700 to-amber-500",
    accentText: "text-amber-800",
    tags: ["Luxury", "ยูนิต", "นัดชมโครงการ"],
    features: ["Hero ภาพลักษณ์พรีเมียม", "แกลเลอรียูนิตและราคา", "ฟอร์มนัดชม / ติดต่อ"],
  },
  {
    slug: "termgame",
    name: "TermGame",
    category: "ขายของ",
    icon: "spark",
    tagline: "ศูนย์รวมเกม ซื้อ · เช่า · เติมเกม",
    description:
      "เว็บไซต์ศูนย์รวมเกมออนไลน์ โชว์เกมยอดนิยมสำหรับซื้อและเช่า รีวิวลูกค้า สถิติความน่าเชื่อถือ และใส่ตะกร้าได้ทันที",
    liveUrl: "https://termgame-iota.vercel.app/",
    preview: "/showcase/termgame.jpg",
    swatch: "from-violet-600 via-fuchsia-500 to-cyan-500",
    accentText: "text-violet-700",
    tags: ["ซื้อเกม", "เช่าเกม", "เติมเกม"],
    features: ["แคตตาล็อกเกมซื้อ/เช่าแยกหมวด", "การ์ดสินค้าพร้อมราคาและรีวิว", "Hero + สถิติ + CTA สมัครสมาชิก"],
  },
  ...OPEN_SOURCE_DEMOS,
];

export function getDemo(slug: string): Demo | undefined {
  return DEMOS.find((d) => d.slug === slug);
}
